"""editable start slots: snapshot assignment coords, SET NULL

Revision ID: a832351bb4bd
Revises: c4be2a139430
Create Date: 2026-07-02 19:41:01.510879
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'a832351bb4bd'
down_revision: str | Sequence[str] | None = 'c4be2a139430'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default backfills existing rows; dropped afterward so the schema
    # matches the model (app always supplies the value).
    op.add_column(
        'prepared_world_assignments',
        sa.Column('start_slot_name', sa.String(length=120), nullable=False, server_default=''),
    )
    op.alter_column('prepared_world_assignments', 'start_slot_name', server_default=None)
    op.add_column('prepared_world_assignments', sa.Column('gps_x', sa.Float(), nullable=True))
    op.add_column('prepared_world_assignments', sa.Column('gps_y', sa.Float(), nullable=True))
    op.add_column('prepared_world_assignments', sa.Column('gps_z', sa.Float(), nullable=True))
    op.alter_column('prepared_world_assignments', 'start_slot_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('prepared_world_assignments_start_slot_id_fkey', 'prepared_world_assignments', type_='foreignkey')
    op.create_foreign_key(None, 'prepared_world_assignments', 'start_slots', ['start_slot_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prepared_world_assignments', type_='foreignkey')
    op.create_foreign_key('prepared_world_assignments_start_slot_id_fkey', 'prepared_world_assignments', 'start_slots', ['start_slot_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('prepared_world_assignments', 'start_slot_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('prepared_world_assignments', 'gps_z')
    op.drop_column('prepared_world_assignments', 'gps_y')
    op.drop_column('prepared_world_assignments', 'gps_x')
    op.drop_column('prepared_world_assignments', 'start_slot_name')
    # ### end Alembic commands ###
