"""initial schema

Revision ID: c4be2a139430
Revises: 
Create Date: 2026-07-02 16:18:47.995464
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c4be2a139430'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('block_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.String(length=200), nullable=False),
    sa.Column('subtype_id', sa.String(length=200), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('pcu', sa.Integer(), nullable=False),
    sa.Column('is_weapon', sa.Boolean(), nullable=False),
    sa.Column('grid_size', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_id', 'subtype_id', name='uq_block_type_subtype')
    )
    op.create_index(op.f('ix_block_definitions_type_id'), 'block_definitions', ['type_id'], unique=False)
    op.create_table('jobs',
    sa.Column('job_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_job_type'), 'jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_jobs_run_after'), 'jobs', ['run_after'], unique=False)
    op.create_index(op.f('ix_jobs_status'), 'jobs', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('member', 'engineer', 'commander', 'admin', name='role', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('game_maps',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_table('ship_classes',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('blueprint_slots',
    sa.Column('ship_class_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ship_class_id'], ['ship_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_slots_ship_class_id'), 'blueprint_slots', ['ship_class_id'], unique=False)
    op.create_table('prepared_worlds',
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('b2_key', sa.String(length=500), nullable=True),
    sa.Column('status', sa.Enum('queued', 'processing', 'ready', 'failed', 'expired', name='prepared_world_status', native_enum=False), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['map_id'], ['game_maps.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepared_worlds_map_id'), 'prepared_worlds', ['map_id'], unique=False)
    op.create_index(op.f('ix_prepared_worlds_status'), 'prepared_worlds', ['status'], unique=False)
    op.create_table('requirements',
    sa.Column('ship_class_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('block_count', 'grid_size', 'pcu_limit', 'weapon_count', 'block_whitelist', 'block_blacklist', name='requirement_type', native_enum=False), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ship_class_id'], ['ship_classes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_ship_class_id'), 'requirements', ['ship_class_id'], unique=False)
    op.create_table('start_slots',
    sa.Column('map_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('position_index', sa.Integer(), nullable=False),
    sa.Column('gps_x', sa.Float(), nullable=False),
    sa.Column('gps_y', sa.Float(), nullable=False),
    sa.Column('gps_z', sa.Float(), nullable=False),
    sa.Column('orient_forward_x', sa.Float(), nullable=True),
    sa.Column('orient_forward_y', sa.Float(), nullable=True),
    sa.Column('orient_forward_z', sa.Float(), nullable=True),
    sa.Column('orient_up_x', sa.Float(), nullable=True),
    sa.Column('orient_up_y', sa.Float(), nullable=True),
    sa.Column('orient_up_z', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['map_id'], ['game_maps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_start_slots_map_id'), 'start_slots', ['map_id'], unique=False)
    op.create_table('blueprints',
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('uploader_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('b2_key', sa.String(length=500), nullable=False),
    sa.Column('thumb_b2_key', sa.String(length=500), nullable=True),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('active', 'replaced', 'cleared', name='blueprint_status', native_enum=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['slot_id'], ['blueprint_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_slot_id'), 'blueprints', ['slot_id'], unique=False)
    op.create_index('uq_blueprint_active_per_slot', 'blueprints', ['slot_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    op.create_table('start_slot_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('start_slot_id', sa.UUID(), nullable=False),
    sa.Column('ship_class_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['ship_class_id'], ['ship_classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_slot_id'], ['start_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('start_slot_id', 'ship_class_id', name='uq_startslot_class')
    )
    op.create_index(op.f('ix_start_slot_classes_ship_class_id'), 'start_slot_classes', ['ship_class_id'], unique=False)
    op.create_index(op.f('ix_start_slot_classes_start_slot_id'), 'start_slot_classes', ['start_slot_id'], unique=False)
    op.create_table('prepared_world_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prepared_world_id', sa.UUID(), nullable=False),
    sa.Column('start_slot_id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['prepared_world_id'], ['prepared_worlds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_slot_id'], ['start_slots.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prepared_world_assignments_prepared_world_id'), 'prepared_world_assignments', ['prepared_world_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prepared_world_assignments_prepared_world_id'), table_name='prepared_world_assignments')
    op.drop_table('prepared_world_assignments')
    op.drop_index(op.f('ix_start_slot_classes_start_slot_id'), table_name='start_slot_classes')
    op.drop_index(op.f('ix_start_slot_classes_ship_class_id'), table_name='start_slot_classes')
    op.drop_table('start_slot_classes')
    op.drop_index('uq_blueprint_active_per_slot', table_name='blueprints', postgresql_where=sa.text("status = 'active'"))
    op.drop_index(op.f('ix_blueprints_slot_id'), table_name='blueprints')
    op.drop_table('blueprints')
    op.drop_index(op.f('ix_start_slots_map_id'), table_name='start_slots')
    op.drop_table('start_slots')
    op.drop_index(op.f('ix_requirements_ship_class_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_prepared_worlds_status'), table_name='prepared_worlds')
    op.drop_index(op.f('ix_prepared_worlds_map_id'), table_name='prepared_worlds')
    op.drop_table('prepared_worlds')
    op.drop_index(op.f('ix_blueprint_slots_ship_class_id'), table_name='blueprint_slots')
    op.drop_table('blueprint_slots')
    op.drop_table('ship_classes')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('game_maps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_jobs_status'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_run_after'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_job_type'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_block_definitions_type_id'), table_name='block_definitions')
    op.drop_table('block_definitions')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
